configure_file(
	${CMAKE_CURRENT_SOURCE_DIR}/cmake/version.rc.in
	${CMAKE_CURRENT_BINARY_DIR}/cmake/version.rc
	@ONLY)

configure_file(
	${CMAKE_CURRENT_SOURCE_DIR}/cmake/Plugin.h.in
	${CMAKE_CURRENT_BINARY_DIR}/cmake/Plugin.h
	@ONLY)

file(GLOB_RECURSE PUBLIC_HEADER_FILES
	LIST_DIRECTORIES false
	CONFIGURE_DEPENDS
	"${CMAKE_CURRENT_SOURCE_DIR}/include/*.h"
	)

file(GLOB_RECURSE HEADER_FILES
	LIST_DIRECTORIES false
	CONFIGURE_DEPENDS
	"${CMAKE_CURRENT_SOURCE_DIR}/src/*.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/external/*.h"
	)

file(GLOB_RECURSE CPP_SOURCE_FILES
	LIST_DIRECTORIES false
	CONFIGURE_DEPENDS
	"${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp"
	"${CMAKE_CURRENT_SOURCE_DIR}/src/*.cc"
	)

set(GENERATED_PLUGIN_FILES
	${CMAKE_CURRENT_BINARY_DIR}/cmake/Plugin.h
	${CMAKE_CURRENT_BINARY_DIR}/cmake/BuildOptions.h
	${CMAKE_CURRENT_BINARY_DIR}/cmake/version.rc)

set(SOURCE_FILES
	${CPP_SOURCE_FILES}
	${GENERATED_PLUGIN_FILES})

# TREE source_group cannot include binary-dir generated files.
source_group("Source"
	TREE ${CMAKE_CURRENT_SOURCE_DIR}
	FILES
	${PUBLIC_HEADER_FILES}
	${HEADER_FILES}
	${CPP_SOURCE_FILES})
source_group("Generated" FILES ${GENERATED_PLUGIN_FILES})
